### ISSUE TITLE
Uploads fail with errorcode 3014

### ISSUE THREAD

**Issue by cabillman** [vmware-tanzu/velero-plugin-for-vsphere#108]
All upload jobs are failing with Error code 3014.  

I'm not sure if this is a bug or a configuration issue but I follow the docs and examples pretty closely. I can't seem to find any reference to error code 3014 in the plugin code. I did see some veeam/vmware references to this and they referenced vsphere permissions. I made the CSI account an administrator to rule that out and still received this error.

CSI 1.0.2
Vmware 6.7U3
Kubernetes: 1.18.3
Velero: 1.4

kubectl describe on an upload object returns the following:
```
Status:
  Current Back Off:      16
  Message:               Failed to upload snapshot, ivd:51935689-4adf-4acd-af7b-5b0d7493e841:fb597016-baa7-48c6-a06c-9fafc4f05c3f, to durable object storage. Prepare for access failed. The error code is 3014. with error code: 3014
  Next Retry Timestamp:  2020-07-02T12:27:32Z
  Phase:                 UploadError
  Processing Node:       test-worker-3
  Progress:
  Retry Count:      5
  Start Timestamp:  2020-07-02T12:04:26Z
```

Here are the logs from the datamgr pod

`
time="2020-07-02T12:11:32Z" level=error msg="Failed to upload snapshot, ivd:51935689-4adf-4acd-af7b-5b0d7493e841:fb597016-baa7-48c6-a06c-9fafc4f05c3f, to durable object storage. Prepare for access failed. The error code is 3014. with error code: 3014" controller=upload generation=9 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:280" name=upload-fb597016-baa7-48c6-a06c-9fafc4f05c3f namespace=velero phase=UploadError
`

**Comment by lintongj** [comment]
@cabillman would you please share the version of velero-plugin-for-vsphere?

Also, please share the VDDK log available on data manager pod running on the node, `test-worker-3`, where the error was observed? The step is shown below.
1. Find the pod. `kubectl -n velero get pods -o wide | grep datamgr | grep test-worker-3 | awk '{print $1}'`
2. Dowload the VDDK log. `kubectl cp velero/<pod name found in step>:/tmp/vmware-root/vixDiskLib-*.log <any path you like>`

`I made the CSI account an administrator to rule that out and still received this error.` What actually did you do for it?

The error code, `3014`, actually indicate an issue of insufficient permission with your vSphere User. Please double check that. Below are a few of relevant articles that might be useful.
- https://www.dell.com/community/Avamar/Error-3014-Image-Backup/td-p/7139182
- https://kb.vmware.com/s/article/2098050
- https://www.veeam.com/kb1937

**Comment by cabillman** [comment]
@lintongj It looks like I did not properly apply the administrator role for testing. I have pulled back the admin role and gave only the additional permissions mentioned in the veeam article. That appears to have fixed the problem.

This was a brand new cluster and I used the following guide to setup the roles and privileges for the csi driver. https://vsphere-csi-driver.sigs.k8s.io/driver-deployment/prerequisites.html#roles_and_privileges

I did not see the additional permissions required for this plugin documented anywhere. Did I overlook something in the docs or would it be helpful to update the Readme?

Thanks again for your help.

**Comment by lintongj** [comment]
> @lintongj It looks like I did not properly apply the administrator role for testing. I have pulled back the admin role and gave only the additional permissions mentioned in the veeam article. That appears to have fixed the problem.
> 
> This was a brand new cluster and I used the following guide to setup the roles and privileges for the csi driver. https://vsphere-csi-driver.sigs.k8s.io/driver-deployment/prerequisites.html#roles_and_privileges
> 
> I did not see the additional permissions required for this plugin documented anywhere. Did I overlook something in the docs or would it be helpful to update the Readme?
> 
> Thanks again for your help.

We have not yet documented the required vSphere role and privilege for velero-plugin-for-vsphere. And we will the Readme accordingly.

**Comment by longwa** [comment]
I'm seeing a different error message in the vixDiskLib-1.log:

```
 VixDiskLib: VixDiskLib_PrepareForAccess: Prepare to access disk.
2020-08-17T16:26:00.078Z| host-45| I125: VixDiskLib: VixDiskLib_Connect: Establish connection.
2020-08-17T16:26:00.078Z| host-45| I125: VixDiskLib: Resolve host.
2020-08-17T16:26:00.406Z| host-45| E110: VixDiskLib: VixDiskLib_PrepareForAccess: Disable Storage VMotion failed. Error 3014 (Insufficient permissions in the host operating system) (No permission to perform this action.) at 5001.
2020-08-17T16:26:00.406Z| host-45| I125: VixDiskLib: VixDiskLib_FreeConnectParams: Free connection parameters.
2020-08-17T16:26:00.618Z| host-41| I125: VixDiskLib: VixDiskLib_PrepareForAccess: Prepare to access disk.
2020-08-17T16:26:00.618Z| host-41| I125: VixDiskLib: VixDiskLib_Connect: Establish connection.
```

I have added the Globals -> License, Globals -> Enable/Disable methods but the error persists (I've restarted datamgr after updating the permissions, not sure if something else would need to be restarted as well).

Any other permissions needed?

**Comment by lintongj** [comment]
> I'm seeing a different error message in the vixDiskLib-1.log:
> 
> ```
>  VixDiskLib: VixDiskLib_PrepareForAccess: Prepare to access disk.
> 2020-08-17T16:26:00.078Z| host-45| I125: VixDiskLib: VixDiskLib_Connect: Establish connection.
> 2020-08-17T16:26:00.078Z| host-45| I125: VixDiskLib: Resolve host.
> 2020-08-17T16:26:00.406Z| host-45| E110: VixDiskLib: VixDiskLib_PrepareForAccess: Disable Storage VMotion failed. Error 3014 (Insufficient permissions in the host operating system) (No permission to perform this action.) at 5001.
> 2020-08-17T16:26:00.406Z| host-45| I125: VixDiskLib: VixDiskLib_FreeConnectParams: Free connection parameters.
> ```
> 
> I have added the Globals -> License, Globals -> Enable/Disable methods but the error persists (I've restarted datamgr after updating the permissions, not sure if something else would need to be restarted as well).
> 
> Any other permissions needed?

please refer to https://github.com/vmware-tanzu/velero-plugin-for-vsphere/issues/156#issuecomment-675041129.

**Comment by lintongj** [comment]
The solution is updated at https://github.com/vmware-tanzu/velero-plugin-for-vsphere/issues/156#issuecomment-675172003. Please kindly close the issue if it helps.

**Comment by lintongj** [comment]
Please find the documentation at https://github.com/vmware-tanzu/velero-plugin-for-vsphere#roles-and-privileges.
