### ISSUE TITLE
Failure on uploads/downloads

### ISSUE THREAD

**Issue by doddatpivotal** [vmware-tanzu/velero-plugin-for-vsphere#149]
I'm working on doing backup/restores with velero as deployed by Tanzu Mission Control.  My upload as result of a backup is complaining with:

`Failed to upload snapshot, ivd:489750af-b01e-4b05-bb39-d5090cb1048f:53b4f953-6e3c-4bca-b8cd-2e71d6610ebf, to durable object storage. Failed to delete peinfo from bucket "vmware-tmc-dp-09965998": Unable to delete object "plugins/vsphere-astrolabe-repo/ivd/peinfo/ivd:489750af-b01e-4b05-bb39-d5090cb1048f:53b4f953-6e3c-4bca-b8cd-2e71d6610ebf" from bucket "vmware-tmc-dp-09965998": MissingRegion: could not find region configuration`

I'm trying to figure out where I can specify region, as I thought I had already done that. Any pointers?

**Comment by lintongj** [comment]
@doddatpivotal Would you please share what did you do to install velero and velero-plugin-for-vsphere?

By design of velero-plugin-for-vsphere v1.0.0 and v1.0.1, volume snapshots will be uploaded to the same S3 bucket as where velero upload backup to. You can also double check whether the region param is set under `spec.config` of velero BackupStorageLocation CR which is used in your `velero backup create` command. Specifically, you can try `velero backup-location get -o yaml`.

**Comment by doddatpivotal** [comment]
I was able to work past this issue when I double checked the region was specified on the backupstoragelocation and restarted the velero pod and data mover pods.  Does this get set during initialization?

Then I faced the next issue where I was getting access denied. in the upload.  Appearently, the cloud credentials managed by TMC's implementation of the velero server have an ondemand password generation/rotation scheme.  My primary backup data would end up in S3, but the snapshot data attempted to be uploaded by the data mover pods were claiming access denied.  I think that is because of a single use password with S3 and velero pod used it, thus invalidating the data-mover pod with using the credential.  As this was not the point of the original issue, we can close it.

**Comment by lintongj** [comment]
> I was able to work past this issue when I double checked the region was specified on the backupstoragelocation and restarted the velero pod and data mover pods. Does this get set during initialization?
> 

Ideally, it is supposed to be set when install velero. If not, you will have to manually edit backupstoragelocation CR.

> Then I faced the next issue where I was getting access denied. in the upload. Appearently, the cloud credentials managed by TMC's implementation of the velero server have an ondemand password generation/rotation scheme. My primary backup data would end up in S3, but the snapshot data attempted to be uploaded by the data mover pods were claiming access denied. I think that is because of a single use password with S3 and velero pod used it, thus invalidating the data-mover pod with using the credential. As this was not the point of the original issue, we can close it.

@doddatpivotal would you please open a new issue about it. It looks like something new we need to take care of. Thanks.

**Comment by lintongj** [comment]
@doddatpivotal would you please also share the version of velero and velero-plugin-for-vsphere in your case?
