### ISSUE TITLE
Airgapped environment setup is not possible

### ISSUE THREAD

**Issue by sharmavijay86** [vmware-tanzu/velero-plugin-for-vsphere#151]
Hey folks i am using velero in an air gapped environment.
I have pull and push all required images in harbor registry and all are working as expected except this vspere plugin.

The problem is

``` velero plugin add harbor.mylab.local/library/velero-plugin-for-vsphere:1.0.1```
data-manager-for-plugin:1.0.1
Failed to pull image "harbor.mylab.local/data-manager-for-plugin:1.0.1": rpc error: code = Unknown desc = failed to pull and unpack image "harbor.mylab.local/data-manager-for-plugin:1.0.1": failed to resolve reference "harbor.mylab.local/data-manager-for-plugin:1.0.1": failed to authorize: failed to fetch anonymous token: unexpected status: 500 Internal Server Error

You see in deployment it is not picking " /Library"  part

**Comment by lintongj** [comment]
@sharmavijay86 

data-manager-for-plugin is an internal component of velero-plugin-for-vsphere. While doing `velero plugin add harbor.mylab.local/library/velero-plugin-for-vsphere:1.0.1`, it would internally pull `data-manager-for-plugin:1.0.1` from the same registry. Would you please double check whether you pushed data-manager-for-plugin image to harbor registry?

**Comment by sharmavijay86** [comment]
@lintongj  Hi yes i have pushed that in same harbor but the problem is it is not picking 'library' part .

**Comment by lintongj** [comment]
> @lintongj Hi yes i have pushed that in same harbor but the problem is it is not picking 'library' part .

@sharmavijay86 Thanks for helping us identify a bug in velero-plugin-for-vsphere v1.0.1. So for, it only handle well image with a single slash "/".

We are going to document this issue in https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/master/FAQ.md and fix this issue in master branch. To workaround your scenario until the fix is made, would you please push images to top inventory of harbor registry, like, harbor.mylab.local/velero-plugin-for-vsphere:1.0.1, etc?

**Comment by sharmavijay86** [comment]
Hey @lintongj  and team. As of now i am doing a workaround as to manually edit daemonset and modify image: section in container: part  or ,   
using rolling update as     
```
kubectl set image ds/<velero-daemonset-name> <container-name>=harbor.mylab.local/library/data-manager-for-plugin:1.0.1 -n velero
```

Which is working in both the above method.
Hope it will get fixed in next release. Thanks.

**Comment by lintongj** [comment]
Hi Xinyan@xinyanw409, please link the issue with the PR that resolves it. Thanks.

**Comment by xinyanw409** [comment]
Fixed this issue in https://github.com/vmware-tanzu/velero-plugin-for-vsphere/pull/157.

**Comment by stephbman** [comment]
For reference - deploying Velero in an air-gapped environment can be found here:  https://velero.io/docs/main/on-premises/
