### ISSUE TITLE
Wrong X.509 Certificate format

### ISSUE THREAD

**Issue by danielkucera** [vmware-tanzu/velero-plugin-for-vsphere#159]
Hello, we are using self-signed certs. but datamgr doesn't seem to be handling them well:
```
time="2020-08-17T07:15:58Z" level=info msg="Enqueueing upload" controller=upload generation=8 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:145" name=upload-5a6806f2-6ecb-48c7-ae18-4d42355bd59f namespace=velero phase=InProgress
2020-08-17T07:15:59.610Z warning -[00017] [Originator@6876 sub=vimaccess] cannot get thumbprint: SSL error code '151441516', exception: 'Wrong X.509 Certificate format'
2020-08-17T07:15:59.611Z warning -[00036] [Originator@6876 sub=Default] Closing Response processing in unexpected state: 3
time="2020-08-17T07:15:59Z" level=error msg="Failed at copying to remote repository" Local PEID="ivd:2579dbe8-6df5-4f21-ae1f-4d10718767bf:5a6806f2-6ecb-48c7-ae18-4d42355bd59f" error="Prepare for access failed. The error code is 3014. with error code: 3014" error.file="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.1-0.20200519042640-570f84703079/pkg/ivd/ivd_protected_entity.go:70" error.function=github.com/vmware-tanzu/astrolabe/pkg/ivd.IVDProtectedEntity.GetDataReader logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/dataMover/data_mover.go:96"
```
Any idea how to fix this?

**Comment by danielkucera** [comment]
I was able to track it down to here:
https://github.com/vmware-tanzu/astrolabe/blob/cbccec55866ecb5b69ba1a8d947b45d153b8e1f3/pkg/ivd/ivd_protected_entity.go#L116

but the gvddk library source is not accessible:
https://github.com/vmware-tanzu/astrolabe/issues/45

I can only guess there is some internal connection to vCenter with missing insecure flag because it seems to not be passed in.

**Comment by lintongj** [comment]
> I was able to track it down to here:
> https://github.com/vmware-tanzu/astrolabe/blob/cbccec55866ecb5b69ba1a8d947b45d153b8e1f3/pkg/ivd/ivd_protected_entity.go#L116
> 
> but the gvddk library source is not accessible:
> [vmware-tanzu/astrolabe#45](https://github.com/vmware-tanzu/astrolabe/issues/45)

I believe you've already figured out where to have access to gvddk source code. 

> 
> I can only guess there is some internal connection to vCenter with missing insecure flag because it seems to not be passed in.

The `Wrong X.509 Certificate format` warning message indicates some SSL issue when velero-plugin-for-vsphere code internally calls VDDK APIs. But it might not be root cause of the upload error with error code 3014. Actually, we did observe the warning message in successful upload case as well.

**Comment by lintongj** [comment]
The solution is updated at https://github.com/vmware-tanzu/velero-plugin-for-vsphere/issues/156#issuecomment-675172003. Please kindly close the issue if it helps.

**Comment by danielkucera** [comment]
You are probably right, those warning seems to be unrelated to the following error.
