### ISSUE TITLE
FailedMount (error processing PVC : PVC is not bound)

### ISSUE THREAD

**Issue by jc0705** [vmware-tanzu/velero-plugin-for-vsphere#180]
Did a velero backup and snapshots on a sample app using the plugin and looks like there is no issue. But upon restoration of the app, it looks like the mounting of PV is unsuccessful as shown under `describe pod` with a endless "ContainerCreating" status. Does anyone know how to solve it by getting the restored containers to mount/attach the PVC without any errors?

**backup describe**
```
$ velero backup describe wordpress-backup --details

Phase:  Completed

Errors:    0
Warnings:  0

Storage Location:  default

Velero-Native Snapshot PVs:  true

Started:    2020-09-09 16:09:37 +0800 +08
Completed:  2020-09-09 16:09:54 +0800 +08

Expiration:  2020-10-09 16:09:37 +0800 +08

Total items to be backed up:  18
Items backed up:              18

Resource List:
  apps/v1/Deployment:
    - wordpress/wordpress
    - wordpress/wordpress-mysql
  apps/v1/ReplicaSet:
    - wordpress/wordpress-747dd64758
    - wordpress/wordpress-mysql-6ccf9b4bb6
  v1/Endpoints:
    - wordpress/wordpress
    - wordpress/wordpress-mysql
  v1/Namespace:
    - wordpress
  v1/PersistentVolume:
    - pvc-a2716ad4-9113-43a9-bc1f-f3ee1450d597
    - pvc-ff40fc3e-235b-4d1a-accc-6d0465184678
  v1/PersistentVolumeClaim:
    - wordpress/mysql-pv-claim
    - wordpress/wp-pv-claim
  v1/Pod:
    - wordpress/wordpress-747dd64758-5ktsr
    - wordpress/wordpress-mysql-6ccf9b4bb6-b5qfv
  v1/Secret:
    - wordpress/default-token-7pf6w
    - wordpress/mysql-pass-ffgtbt8k66
  v1/Service:
    - wordpress/wordpress
    - wordpress/wordpress-mysql
  v1/ServiceAccount:
    - wordpress/default

Velero-Native Snapshots:
  pvc-a2716ad4-9113-43a9-bc1f-f3ee1450d597:
    Snapshot ID:        ivd:a2350ffa-a7f6-439d-82c3-9bcb15d2e333:3e6a98e3-372d-48ff-a474-e3322d1922fe
    Type:               ivd
    Availability Zone:
    IOPS:               100
  pvc-ff40fc3e-235b-4d1a-accc-6d0465184678:
    Snapshot ID:        ivd:8e2a0069-02b9-42c7-a346-c126928aa207:a677342d-8adf-4cf0-9439-676ce9adf562
    Type:               ivd
    Availability Zone:
    IOPS:               100
```

**restore describe**
```
$ velero restore describe wordpress-backup-20200909160413
Name:         wordpress-backup-20200909160413
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:     PartiallyFailed (run 'velero restore logs wordpress-backup-20200909160413' for more information)
Warnings:  <error getting warnings: file not found>

Errors:  <error getting errors: file not found>

Backup:  wordpress-backup

Namespaces:
  Included:  all namespaces found in the backup
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto
```

**restore logs**
```
$ velero restore logs wordpress-backup-20200909160413
An error occurred: file not found
```

**describe pod**
```
$ kubectl describe pod wordpress-747dd64758-5ktsr -n wordpress

Events:
  Type     Reason       Age                             From                                           Message
  ----     ------       ----                            ----                                           -------
  Normal   Scheduled    <invalid>                       default-scheduler                              Successfully assigned wordpress/wordpress-747dd64758-5ktsr to 2ba3e7b7-750f-4038-8339-0340e959d4a1
  Warning  FailedMount  <invalid> (x2 over <invalid>)   kubelet, 2ba3e7b7-750f-4038-8339-0340e959d4a1  Unable to attach or mount volumes: unmounted volumes=[wordpress-persistent-storage], unattached volumes=[default-token-69ck5 wordpress-persistent-storage]: error processing PVC wordpress/wp-pv-claim: PVC is not bound
  Warning  FailedMount  <invalid> (x14 over <invalid>)  kubelet, 2ba3e7b7-750f-4038-8339-0340e959d4a1  Unable to attach or mount volumes: unmounted volumes=[wordpress-persistent-storage], unattached volumes=[wordpress-persistent-storage default-token-69ck5]: error processing PVC wordpress/wp-pv-claim: PVC is not bound
```
**storage class**
```
$ kubectl get sc
NAME                         PROVISIONER                    AGE
csi-storageclass (default)   csi.vsphere.vmware.com         6h9m
```

**Comment by lintongj** [comment]
@jc0705 

Would you please share velero & velero-plugin-for-vsphere versions? Also, would you please share the following logs?

1. velero deployment log: `kubectl -n velero logs deploy/velero`
2. plugin download CRs: `kubectl -n velero get downloads -o yaml`
3. data manager pod logs: `kubectl -n velero logs pod/datamgr-XXX`
4. vSphere CSI driver log

Thanks.

**Comment by jc0705** [comment]
- `velero version`
```
Client:
        Version: v1.4.2
        Git commit: 56a08a4d695d893f0863f697c2f926e27d70c0c5
Server:
        Version: v1.4.2
```

- data-manager-for-plugin & velero-plugin-for-vsphere version : 1.0.1

1. velero deployment log: `kubectl -n velero logs deploy/velero`
[velero logs.txt](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/files/5205636/velero.logs.txt)

2. plugin download CRs: `kubectl -n velero get downloads -o yaml`

```
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

3. data manager pod logs: `kubectl -n velero logs pod/datamgr-XXX`
[datamgr logs.txt](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/files/5205641/datamgr.logs.txt)
[datamgr logs2.txt](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/files/5205642/datamgr.logs2.txt)



4. vSphere CSI driver log (not really sure where do i get this?)

**Comment by lintongj** [comment]
> vSphere CSI driver log (not really sure where do i get this?)

Please try, `kubectl logs vsphere-csi-controller-0 --all-containers=True -n kube-system`. But, in your case, it doesn't seem to be a volume provisioning issue. The failure occurs far before provisioning volume.

As far as I can see from logs you provided,

>$grep -nr "starting restore" velero.logs.txt
>velero.logs.txt:454:time="2020-09-11T02:07:00Z" level=info msg="starting restore" logSource="pkg/controller/restore_controller.go:453" restore=velero/wordpress-backup-20200911095348

There is only one restore, `wordpress-backup-20200911095348`, can be found. That being said, the restore request, `wordpress-backup-20200909160413`, didn't even reach velero server. That is also the reason why the list of downloads (the CR of velero-plugin-for-vsphere in the restore process) turns out to be empty. 

At the end of the velero log, `velero.logs.txt`, the issue about `XMinioStorageFull: Storage backend has reached its minimum free disk threshold.` was declared. 

>time="2020-09-11T02:27:00Z" level=error msg="Error uploading restore results to backup storage" controller=restore error="rpc error: code = Unknown desc = error putting object restores/wordpress-backup-20200911095348/restore-wordpress-backup-20200911095348-results.gz: XMinioStorageFull: Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed.\n\tstatus code: 507, request id: 163399A3A59C2A8C, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:257" error.function="main.(*ObjectStore).PutObject" logSource="pkg/controller/restore_controller.go:497"

Please double check your Minio object store and make sure it is working fine.

**Comment by jc0705** [comment]
The problem is indeed with the storage of the Minio object store... Looks like you have to allocate at least twice the space of the PVC for the Minio object store... Thanks for your help!
