### ISSUE TITLE
Disabled migration during backup

### ISSUE THREAD

**Issue by danielkucera** [vmware-tanzu/velero-plugin-for-vsphere#182]
When doing the backup, gvddk calls PrepareForAccess and fails if it is not sucessfull:
https://github.com/vmware-tanzu/astrolabe/blob/master/vendor/github.com/vmware/gvddk/gvddk-high/gvddk.go#L49

PrepareForAccess ( [see docs](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/8f96698a-0e7b-4d67-bb6c-d18a1d101540/ef536a47-27cd-481a-90ef-76b38e75353c/doc/GUID-A0557282-DE08-4E88-B87E-19D28CBD3394.html) ) `disables the vSphere API method RelocateVM_Task` which means the migration is not possible during this time and it also requires quite high privileges on vCenter (see resulting problems #156 and #108 and here https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blame/master/README.md#L21)

First of all, as we don't administer our vSphere platform, our admins are very conservative about giving out privileges especially so high so we are not able to get these.
Second point is that if some failure condition happens, we won't be able to migrate the machine if it will be in the middle of long backup process which can affect our availability. We would much more prefer failing the backup and being able to migrate the machine anytime.

To make the backup work, I have patched gvddk like this:
```
--- a/vendor/github.com/vmware/gvddk/gvddk-high/gvddk.go
+++ b/vendor/github.com/vmware/gvddk/gvddk-high/gvddk.go
@@ -48,7 +48,8 @@ func OpenFCD(serverName string, thumbPrint string, userName string, password str
 func Open(globalParams gDiskLib.ConnectParams, logger logrus.FieldLogger) (DiskReaderWriter, gDiskLib.VddkError) {
        err := gDiskLib.PrepareForAccess(globalParams)
        if err != nil {
-               return DiskReaderWriter{}, err
+               logger.Warningf("Prepare For Access ended with '%s'\n", err)
+               //return DiskReaderWriter{}, err
        }
        conn, err := gDiskLib.ConnectEx(globalParams)
        if err != nil {
@@ -330,4 +331,4 @@ func (this DiskConnectHandle) Close() error {

 func (this DiskConnectHandle) Capacity() int64 {
        return int64(this.info.Capacity) * gDiskLib.VIXDISKLIB_SECTOR_SIZE
```

What is your opinion about this change?

**Comment by lintongj** [comment]
@danielkucera does the patch work well in your backup tasks? 

Basically, the operation of `disables the vSphere API method RelocateVM_Task` is a prerequisite of a VDDK connection specified in the VDDK document, not a constraint introduced by velero-plugin-for-vsphere. We would suggest you to follow that for now. 

> Second point is that if some failure condition happens, we won't be able to migrate the machine if it will be in the middle of long backup process which can affect our availability. We would much more prefer failing the backup and being able to migrate the machine anytime.

Enabling the backup while virtual disks are migrating is a feature request in VDDK. We will convey it to VDDK team and see if there is any plan and if it is doable. But, it could not be an easy change.

**Comment by lintongj** [comment]
Close this issue as no more follow-up question for a while.
