### ISSUE TITLE
Commercial support

### ISSUE THREAD

**Issue by danielkucera** [vmware-tanzu/velero-plugin-for-vsphere#188]
Hello,

I'd like to know if there is some way how to get commercial support for this plugin. We are really interested in it and would like to go to production with this backup solution.

Thank you.

**Comment by dsu-igeek** [comment]
Thanks for the interest and thanks for your feedback on and use of the plug-in and Velero!

Support for Velero and the Velero Plug-in for vSphere is part of the VMWare Tanzu Toolkit for Kubernetes (https://docs.vmware.com/en/VMware-Tanzu-Toolkit-for-Kubernetes/index.html).  Please contact your VMWare sales rep for pricing, etc.

**Comment by lintongj** [comment]
Close this issue as no more follow-up question for a while.
