### ISSUE TITLE
the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)

### ISSUE THREAD

**Issue by tirelibirefe** [vmware-tanzu/velero-plugin-for-vsphere#218]
I've Velero 1.5.2 installed on Kubespray Kubernetes 1.18 on Vsphere 6.7 u3.

This is my installation:

```
velero install  \
--secret-file ./credentials-velero \
--image velero/velero:v1.5.2 \
--provider aws \
--bucket velero \
--plugins velero/velero-plugin-for-aws:v1.1.0,velero/velero-plugin-for-csi:v0.1.2 \
--backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://"$(kubectl get service minio -n minio | awk 'NR > 1 {print "" $3 ""}')":9000 \
--use-restic \
--use-volume-snapshots=false

```
and enabled plugin support:

```
velero plugin add vsphereveleroplugin/velero-plugin-for-vsphere:1.0.2
velero snapshot-location create vsl-vsphere --provider velero.io/vsphere
```

Regarding the documentation ; my system meets the requirements:

My vsphere csi drivers:

```
Image:         quay.io/k8scsi/csi-attacher:v1.1.1
Image ID:      docker-pullable://quay.io/k8scsi/csi-attacher@sha256:e4db94969e1d463807162a1115192ed70d632a61fbeb3bdc97b40fe9ce78c831
Image:         gcr.io/cloud-provider-vsphere/csi/release/driver:v1.0.2
Image ID:      docker-pullable://gcr.io/cloud-provider-vsphere/csi/release/driver@sha256:149e87faaacda614ee95ec271b54c8bfdbd2bf5825abc12d45c654036b798229
Image:         quay.io/k8scsi/livenessprobe:v1.1.0
Image ID:      docker-pullable://quay.io/k8scsi/livenessprobe@sha256:dde617756e0f602adc566ab71fd885f1dad451ad3fb063ac991c95a2ff47aea5
Image:         gcr.io/cloud-provider-vsphere/csi/release/syncer:v1.0.2
Image ID:      docker-pullable://gcr.io/cloud-provider-vsphere/csi/release/syncer@sha256:4b36adf433b98aa84a8f2e58db1b3bea8dfcb05ee56e65c9e9388d56c25e8647
Image:         quay.io/k8scsi/csi-provisioner:v1.2.2
Image ID:      docker-pullable://quay.io/k8scsi/csi-provisioner@sha256:e3239de37c06d2bcd0e9e9648fe9a8b418d5caf9e89f243c649ff2394d3cbfef
```

Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

I've also set vSphere Roles and Privileges as desribed in documentation.

The problem is that when I attempt to backup sample nginx-example with pv statefull application` velero backup create backup1 --include-namespaces=nginx-example --snapshot-volumes --volume-snapshot-locations vsl-vsphere` , the backup gets time-out and reports following error:

`error getting VolumeSnapshotContent objects for backup backup1: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)`

Could you please advise what I'm missing?

**Comment by lintongj** [comment]
@tirelibirefe 

Please try `velero install` without `velero/velero-plugin-for-csi:v0.1.2` plugin if you would like to use vsphere plugin v1.0.2. The error message was actually thrown from velero-plugin-for-csi.

**Comment by dervistalha** [comment]
@lintongj thank you very much for your advise. 
Yesterday I tried several different configurations. Your advise worked but not for problem `the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)`

The cause of problem the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io) is missing csi drivers. Neither Kubespray nor Kubernetes  1.18 has built-in csi drivers. Regarding to 
![image](https://user-images.githubusercontent.com/71238946/97229242-190c7e00-17e9-11eb-805d-f382d73d2447.png) I installed csi drivers and the problem disappeared.

Additionally There was another problem related with with snapshotting. I am not able to paste logs here as I deleted them. I re-installed velero without `velero/velero-plugin-for-csi:v0.1.2` and the problem has gone.

Things work but there are still some points I haven't understood yet. The documentation is missing and not clear enough. Maybe my bad.

1) Why do I had to install additional csi drivers to my Kubernetes 1.18 although vsphere-csi drivers were already installed? This point is not mentioned in documentation.

2) If velero-plugin-for-csi is platform agnostic, why it doesn't work on vsphere and need to install/use vsphereveleroplugin/velero-plugin-for-vsphere?

Thanks

**Comment by tirelibirefe** [comment]
@lintongj thank you very much for your advise.
Yesterday I tried several different configurations. Your advise worked but not for problem `the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)`

The cause of problem the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io) is missing csi drivers. Neither Kubespray nor Kubernetes 1.18 has built-in csi drivers. Regarding to
[https://github.com/vmware-tanzu/velero-plugin-for-vsphere](https://github.com/vmware-tanzu/velero-plugin-for-vsphere) , I installed csi drivers and the problem disappeared.

Additionally There was another problem related with with snapshotting. I am not able to paste logs here as I deleted them. I re-installed velero without `velero/velero-plugin-for-csi:v0.1.2` and the problem has gone.

Things work but there are still some points I haven't understood yet. The documentation is missing and not clear enough. Maybe my bad.

1. Why do I had to install additional csi drivers to my Kubernetes 1.18 although vsphere-csi drivers were already installed? This point is not mentioned in documentation.

2. If velero-plugin-for-csi is platform agnostic, why it doesn't work on vsphere and need to install/use `vsphereveleroplugin/velero-plugin-for-vsphere`?

Thanks

**Comment by lintongj** [comment]
Glad to know that it helps.

> 1. Why do I had to install additional csi drivers to my Kubernetes 1.18 although vsphere-csi drivers were already installed? This point is not mentioned in documentation.

That is a question to `velero-plugin-for-csi`. Please feel free to refer to https://velero.io/docs/v1.5/csi/ or ask question at https://github.com/vmware-tanzu/velero-plugin-for-csi/issues. 

FYI, velero-plugin-for-vsphere doesn't have dependency on velero-plugin-for-csi.

> 2. If velero-plugin-for-csi is platform agnostic, why it doesn't work on vsphere and need to install/use `vsphereveleroplugin/velero-plugin-for-vsphere`?
> 

`velero-plugin-for-csi` relies on the CSI volumesnapshotting APIs in upstream Kubernetes, which is still not GA'ed yet. In vSphere CSI driver, the CSI snapshot support is not ready yet. Until that happens, velero-plugin-for-vsphere would always be the first option for velero backup/restore on vSphere.
