### ISSUE TITLE
broken link for Create a VolumeSnapshotLocation in the Installing the plugin section

### ISSUE THREAD

**Issue by eveane** [vmware-tanzu/velero-plugin-for-vsphere#239]
https://github.com/vmware-tanzu/velero-plugin-for-vsphere#Install-the-plugin

Installing the plugin
Install Velero - please see the Velero documentation https://velero.io/docs/v1.3.1/basic-install
Install the AWS plugin
Install the plugin
Create a VolumeSnapshotLocation 
Backup using the plugin

Create a VolumeSnapshotLocation point to :https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/master/Create-a-VolumeSnapshotLocation which return 404

it should point to https://github.com/vmware-tanzu/velero-plugin-for-vsphere/#create-a-volumesnapshotlocation

**Comment by lintongj** [comment]
@eveane 

Would you please share where did you find the broken link?

In my case, both of the following case work as expected,

1. in the home page of https://github.com/vmware-tanzu/velero-plugin-for-vsphere, the link points to https://github.com/vmware-tanzu/velero-plugin-for-vsphere/#create-a-volumesnapshotlocation
2. in the readme file, https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/master/README.md, the link points to https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/master/README.md#create-a-volumesnapshotlocation

**Comment by eveane** [comment]
I still have the issue, see the screen shot and the link i hovering :
![image](https://user-images.githubusercontent.com/48088600/99830701-fbb3a100-2b55-11eb-9c87-02a2e6ac0a96.png)
