### ISSUE TITLE
cannot use custom certificate in air gapped environment 

### ISSUE THREAD

**Issue by amos-baron** [vmware-tanzu/velero-plugin-for-vsphere#317]
[A clear and concise description of what the bug is]

after creating the backup with : 
`velero snapshot-location create vsl-vsphere --provider velero.io/vsphere`
 the backup completes as expected and the i can see the backup and snapshot files int he bucket.

when trying to restore from backup the restore is stuck on "in progress" and the backup-driver logs:
> "send request failed caused by : get https://mys3storage/velero/plugins/vsphere-astrikabe-repo/ivd x509 certificate signed by unknown authority "

[Steps to reproduce the behavior]
create a custom pem encoded ca bundle that includes the s3 storage

I installed velero with : 
`velero install \
 --provider aws \
 --plugins velero/velero-plugin-for-aws:v1.1.0 \
 --bucket velero2  \
 --secret-file ./credentials-velero  \
 --use-volume-snapshots=true \
 --backup-location-config region=default,s3ForcePathStyle="true",s3Url=http://minio.10.x.y.z.nip.io  \
 --image velero/velero:v1.5.3  \
 --snapshot-location-config region="default" `

and the plugin with :
`velero plugin add vsphereveleroplugin/velero-plugin-for-vsphere:1.1.0
`

then create the snapshot location :

`velero snapshot-location create vsl-vsphere --provider velero.io/vsphere`

[A clear and concise description of what you expected to happen]
the restore to work as expected with the custom ca bundle

[Miscellaneous information that will assist in solving the issue]
how do i get the plugin to trust my custom ca bundle

**Comment by amos-baron** [comment]
just found [this](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/pull/315), does it mean that this is not supported ?

**Comment by lintongj** [comment]
> just found [this](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/pull/315), does it mean that this is not supported ?

Not yet. The support will come with the next patch release. ETA: End of March.
