### ISSUE TITLE
problems with velero-vsphere-plugin in air-gapped environment 

### ISSUE THREAD

**Issue by amos-baron** [vmware-tanzu/velero-plugin-for-vsphere#320]
[A clear and concise description of what the bug is]
plugin does not upload snapshots to the s3 storage.
after creating a backup the upload resource phase is 

> Upload error

with the messege 

>  Failed to upload snapshot ivd:[some random sequence] to durable object storage. open virtual disk file failed. with the error code 14009

and the snapshot resource phase is uploadFailed.

[Steps to reproduce the behavior]
- install Velero in an air gapped environment on an Openshift using the velero install command with the aws plugin and providing it the custom ca bundle my s3 provider uses
- add the vsphere plugin velero with the velero plugin command 
`velero plugin add vsphereveleroplugin/velero-plugin-for-vsphere:1.1.0 `
- copied my custom s3 ca to /etc/ssl/certs in images of the backup-driver and the data-manager so it trusts it ( as the plugin does not yet provide a solution for this problem.
- created snapshot location 
`velero snapshot-location create vsl-vsphere --provider velero.io/vsphere`

- try to backup namespace 
`velero backup create snapshot-mongodb --include-namespaces=test-backup\
--snapshot-volumes --volume-snapshot-locations vsl-vsphere
`

[A clear and concise description of what you expected to happen]
i expect the snapshot to finish and upload successfully to the s3 storage 

[Miscellaneous information that will assist in solving the issue]
in addition when viewing the  logs in /tmp/vmware-root/vixDiskLib-1.log in one of the data-mgr pod i see a lot of errors regarding missing vmware setting files in the image.
for example 

> cannt open file "/etc/vmware/vsphereFeatures/techFeatures/techPreview.cfg" No such file or directory
but it looks as it uses default values instead 

also in the logs of the vsphere-plugin in the velero pod i can see that the plugin cannot get the  tag of the image and uses the default csi version instead (v1.0.2) when in reality our csi version is 2.0.1
[troubleshooting]
velero version server: v1.5.3 client:v1.5.3
velero client config get features: <not set>
kubernetes version: v1.19 under openshift 4.6
csi version: v2.0.1
vsphere version: 6.7u

**Comment by lintongj** [comment]
Thanks for reporting this issue. A few comments here.

1. When using velero-plugin-for-vsphere 1.1.0, please do not create and use snapshot location, `velero.io/vsphere`. Reference: https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/main/docs/vanilla.md#backup-vsphere-cns-block-volumes 
2. The `No such file or directory` errors found in the vixDiskLib log can be just ignored. They are just expected log from VDDK lib consumed by velero-plugin-for-vsphere.
3. `the plugin cannot get the tag of the image and uses the default csi version instead (v1.0.2) when in reality our csi version is 2.0.1` It will not have any side-effect.
4. When you see `14009` failure in upload, it usually means the expected port 902 was not opened on ESXi hosts. Please refer to https://github.com/vmware-tanzu/velero-plugin-for-vsphere/pull/308 about network requirement.
5. Please refer to https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/main/docs/troubleshooting.md#generalvanilla and collect logs about the issue. Without log, we can debug effectively.

**Comment by amos-baron** [comment]
[debug]
`kubectl -n <velero namespace> logs deploy/velero `
only shows 

> checking for existing backup locations ready to be verified there needs to be at least 1 backup location available

which is not a problem as shown [here](https://github.com/vmware-tanzu/velero/issues/2942) 

`velero backup/restore get/describe <name>

> spec: 
       default Volume To Restic: true
    Hooks:
     Included Namespaces: 
             test-backup
    snapshot volumes: true
    storage location: default 
     ttl: 720h0m0s
     Volume Snapshot Locations: 
        vs1-vsphere

`kubectl -n <velero namespace> logs deploy/backup-driver`

>  level=error msg="peType,  , is not avialble log source= ."......"
level=error msg="Failed to get the cmponenets from peID pvc:test-backup/mongodb error could not find subcomponent peid for pvc:test-backup/mongodb "
level= error msg=could not get protected entity for pv [random sequence]: PeType is not avialable error.file="/.././/.//" error.function "github.com/../.././" (*directProtectedEntityManager).GetProtectedEntity
level=error msg="failed at calling snapshotManager=CloneFromSnapshot with peid pvc:test=backup/mongodb controller=backupdriver.....

and many more error regarding the snapshot with many of them specifiing " could not find subcomponent PEID for pvc:test-backup/mongodb test-backup mongodb could not get protected entity for pv"

`kubectl -n velero logs pod/<data manager pod name>`

> faield at copying to remote repository Local PEID="ivd:random sequence" error="open virtual disk failed the error code is 14009"
CopyToRepo Error recieved open virtual disk file failed to error code is 14009 with error code 14009 
warning please fix the network issue on the work node mynodedns contoller=upload generation=82 name=upload-[random sequence] 
level error msg="Error in syncHandler re-adding item to queue"


FYI i copied these logs by hand because i work in an a disconnected environment so there might be spelling mistakes on my part if there are any logs i should expend on please tell me

**Comment by lintongj** [comment]
1. `level=error msg="peType, , is not avialble log source= ."......"` could happen if the backup-driver lost VC connection when it is boot up. Internally, backup-driver will try to get a VCenter session once and will not refresh after that(Will fix that in future release though). This issue could be resolved by restarting backup-driver deployment. To confirm this issue, the first 50 line of backup-driver would be helpful.
2. `CopyToRepo Error recieved open virtual disk file failed to error code is 14009 with error code 14009
warning please fix the network issue on the work node mynodedns`. There is network issue in your cluster. Please open port 902 on ESX hosts.

**Comment by amos-baron** [comment]
I have opened port 902 on all hosts and now when i use `tcpdump -i [datamgr pod virtual interface]` on a node i can see that the data manager and the Virtual center are communicating but still the upload fails. it seems as tho the backupdriver should create a bucket in the s3:
> created s3 repo type=ivd bucket=velero prefix=plugins/vsphere-astrolabe-repo

but later when it tries to upload the snapshot it shows:
> failed to get the source snapshot PE for peID ivd:[random sequence] error="GetObject failed for bucket velero key plugins/vsphere-astrolabe-repo/ivd/peinfo/ivd no such key the specified key does not exist"

when I look in the s3 i cannot see plugins/vsphere-astrolabe-repo in the velero bucket so i think it fails to create it.

**Comment by amos-baron** [comment]
> 1. `level=error msg="peType, , is not avialble log source= ."......"` could happen if the backup-driver lost VC connection when it is boot up. Internally, backup-driver will try to get a VCenter session once and will not refresh after that(Will fix that in future release though). This issue could be resolved by restarting backup-driver deployment. To confirm this issue, the first 50 line of backup-driver would be helpful.


the first ~50 look to be ordinary to me and its difficulted to copy them all by hand so ill abbreviate some : 

> starting backup driver 
backup-driver server is started 
snapshotmanager vsphere vs credential is retrivied
initializing IVD protected entity manager
loading new ivd protected entity manger 
detected virtualcenterconfig change during periodic reload
attempting login for user myuser@vsphere.local
new session id for 'VSPHERE.LOCAL\\myuser
initializing VSLM manager
initializing new VslmMnager
initializing new CnsMnager
glibc malloc guards disabled
initialized systemfactory 
unrecognized log/level '' using info
loggin uses fast path: true
dictionaryLoad connot open file /etc/vmware/vsphereFeatures/techPreview.cfg no such file or directory using defaults
the bora/lib logs WILL be handled by vmacore
and many more info logs of this nature
'

**Comment by lintongj** [comment]
> > 1. `level=error msg="peType, , is not avialble log source= ."......"` could happen if the backup-driver lost VC connection when it is boot up. Internally, backup-driver will try to get a VCenter session once and will not refresh after that(Will fix that in future release though). This issue could be resolved by restarting backup-driver deployment. To confirm this issue, the first 50 line of backup-driver would be helpful.
> 
> the first ~50 look to be ordinary to me and its difficulted to copy them all by hand so ill abbreviate some :
> 
> > starting backup driver
> > backup-driver server is started
> > snapshotmanager vsphere vs credential is retrivied
> > initializing IVD protected entity manager
> > loading new ivd protected entity manger
> > detected virtualcenterconfig change during periodic reload
> > attempting login for user [myuser@vsphere.local](mailto:myuser@vsphere.local)
> > new session id for 'VSPHERE.LOCAL\myuser
> > initializing VSLM manager
> > initializing new VslmMnager
> > initializing new CnsMnager
> > glibc malloc guards disabled
> > initialized systemfactory
> > unrecognized log/level '' using info
> > loggin uses fast path: true
> > dictionaryLoad connot open file /etc/vmware/vsphereFeatures/techPreview.cfg no such file or directory using defaults
> > the bora/lib logs WILL be handled by vmacore
> > and many more info logs of this nature
> > '

These log indicates that backup-driver is booted up as expected.

**Comment by lintongj** [comment]
> I have opened port 902 on all hosts and now when i use `tcpdump -i [datamgr pod virtual interface]` on a node i can see that the data manager and the Virtual center are communicating but still the upload fails. it seems as tho the backupdriver should create a bucket in the s3:
> 
> > created s3 repo type=ivd bucket=velero prefix=plugins/vsphere-astrolabe-repo
> 
> but later when it tries to upload the snapshot it shows:
> 
> > failed to get the source snapshot PE for peID ivd:[random sequence] error="GetObject failed for bucket velero key plugins/vsphere-astrolabe-repo/ivd/peinfo/ivd no such key the specified key does not exist"
> 
> when I look in the s3 i cannot see plugins/vsphere-astrolabe-repo in the velero bucket so i think it fails to create it.

You mentioned `the upload fails`, but you could still see the following log messages.

```
level=error msg="failed at calling snapshotManager=CloneFromSnapshot with peid pvc:test=backup/mongodb controller=backupdriver.....
```
and
```
failed to get the source snapshot PE for peID ivd:[random sequence] error="GetObject failed for bucket velero key plugins/vsphere-astrolabe-repo/ivd/peinfo/ivd no such key the specified key does not exist"
```

The two log messages should only be seen when restore operation is called. Can you confirm if there is also a restore operation running together with the backup operation? That is not an expected use case. Additionally, the error log about `GetObject failed` could happen if the restore operation is called before uploads are completed. 

My suggestion is, please delete any InProgress CRs, `backup`, `restore`, `upload` and `download` first. And run a new backup & restore workflow.

1. run `velero backup create ...` and monitor the `upload` CRs until all `uploads` are `Completed` in status. 
2. delete your application to mock a disaster. 
3. run `velero restore create ...`

**Comment by amos-baron** [comment]
> The two log messages should only be seen when restore operation is called. Can you confirm if there is also a restore operation running together with the backup operation? That is not an expected use case. Additionally, the error log about `GetObject failed` could happen if the restore operation is called before uploads are completed.


I have tried to restore before but i have deleted all of the resources that might cause these logs to appear ( restores, uploads,downloads, snapshots ) my solution was to just reinstall the plugin and it fixed it.

**Comment by amos-baron** [comment]
> 2. `CopyToRepo Error recieved open virtual disk file failed to error code is 14009 with error code 14009 warning please fix the network issue on the work node mynodedns`. There is network issue in your cluster. Please open port 902 on ESX hosts.

I have reinstalled the plugin and opened the esxi on port 902 both from the VC segment and the segment where velero runs. 
still i see error code 14009, is there any other port i might need to open? keep in mind i work in an air gapped environment with a firewall  so any communication is not trivial.
here are the logs from the data manager on the node where the pv is mounted: random

> Trying to back independent PV from volume ID ivd:[]
current node myopenshiftnode exxpected node for uploading the upload CR myopenshiftnode 
attempting to acquire leader lease velero/upload-lease.upload
successfully acquired lease velero/upload-lease.upload
lock is acquired by current node myopenshiftnode to process Upload upload[random]
upload starting
upload status updated from New to InProgress
Using expicitly found credentials for S3 repository access
got true for s3 repo type=ivd bucket=velero prefix=plugins/vsphere-astrolabe-repo
copying the snapshot from local to remote repository access
got true for s3ForcePathStyle setting s3ForcePathStyle to true
created s3 repo type ivd bucket=velero prefix=plugins/vsphere-astrolabe=repo
 
its worth the mention I do not see the repo created in the s3 storage

> Copying the snapshot from local to remote repository
registering a in progress cancel function
registered a on going cancel function
trying to back independent PV from volume ID
Invalid Service registration info for ServiceProduct: com.vmware.ph ServiceType: phservice EndPointType: com.vmware.ph.ceip.api.state
endpoint not found for Product: com.vmware.ph type ph service endpointType: com.vmware.ph.ceip.api.state
could not get CCS endpoint URL treat CEIP as disabled
failed at copying to remote repository error=open virtual disk file failed the error code is 14009 
error in syncHandler re-adding item to queue controller upload errorFailed to upload snapshot
RE adding failed upload to queue
fauled to upload to the queue
attempting to aquire leader leace
successfully acquire lease ve
lock is aquired by current node

**Comment by lintongj** [comment]
>I have reinstalled the plugin and opened the esxi on port 902 both from the VC segment and the segment where velero runs.
still i see error code 14009, is there any other port i might need to open?

I would suggest to open port 902 on all ESXi hosts and allow both incoming and outgoing traffic from the all the k8s worker nodes. 

I assume you are running in a Vanilla k8s on vSphere, which means you don't use any of vSpher with tanzu, or Tanzu Kubernetes Grid service. In this case, the data manager pod which is running on the same k8s worker node where the PV is attached will take the upload operation. Internally, data manager pod uses VDDK NBD mode to access snapshot data of PV(i.e, VMDK). However, by design of VDDK NBD mode, the ESX that actually access the snapshot data may not be the ESX that hosts the worker node (VM) where the PV is attached. That's why I make the suggestion above.

>its worth the mention I do not see the repo created in the s3 storage

That is expected in your case. The failure happens in reading data from VMDK which is before upload to s3 happens. So, it is reasonable not to see the `vsphere-astrolabe-repo` since no object is uploaded yet.

**Comment by amos-baron** [comment]
> > I have reinstalled the plugin and opened the esxi on port 902 both from the VC segment and the segment where velero runs.
> > still i see error code 14009, is there any other port i might need to open?
> 
> I would suggest to open port 902 on all ESXi hosts and allow both incoming and outgoing traffic from the all the k8s worker nodes. Data manager runs as a Daemonset, so each worker node runs a data manager pod.
> 
> I assume you are running in a Vanilla k8s on vSphere, which means you don't use any of vSpher with tanzu, or Tanzu Kubernetes Grid service. In this case, the data manager pod which is running on the same k8s worker node where the PV is attached will take the upload operation. Internally, data manager pod uses VDDK NBD mode to access snapshot data of PV(i.e, VMDK). However, by design of VDDK NBD mode, the ESX that actually access the snapshot data may not be the ESX that hosts the worker node (VM) where the PV is attached. That's why I make the suggestion above.
> 
> > its worth the mention I do not see the repo created in the s3 storage
> 
> That is expected in your case. The failure happens in reading data from VMDK which is before upload to s3 happens. So, it is reasonable not to see the `vsphere-astrolabe-repo` since no object is uploaded yet.

first, thank you for the quick reply.
I am running on an openshift cluster but i have used the vanilla k8s installation guide as reference, what network policy should I be adding. i have added an egress network policy to allow egress communication on port 902 and have opened firewall rules between the vc and esxi on 902 and the ocp node and the esxi on 902.
as ive said using tcpdump on the virtual interface of one of the datamanager pods / backup-driver (cant remember which it was ) ive managed to see syn and ack between the pod and the VC

**Comment by lintongj** [comment]
>as ive said using tcpdump on the virtual interface of one of the datamanager pods / backup-driver (cant remember which it was ) ive managed to see syn and ack between the pod and the VC

The connection between pod and VC is not sufficient here. Please make sure the connection between ESXi hosts and data manager pods is working, since the data path of backup & restore workflow bypasses VC.

**Comment by amos-baron** [comment]
> is not sufficient here. Please make sure the connection between

I have opened ports 902 between the pods and the esxi machines 
what ports do i need to open from pod segment to the VC segment

**Comment by lintongj** [comment]
>what ports do i need to open from pod segment to the VC segment

Port 443 on VC, which is used to call VC APIs from pod.

**Comment by amos-baron** [comment]
> > what ports do i need to open from pod segment to the VC segment
> 
> Port 443 on VC, which is used to call VC APIs from pod.


ive opened port 443 for TCP and UDP with a network policy and on the firewall. when i do telnet to my VC on 443 I see its connected. I have also added the vc ssl cert to the images on /etc/ssl/certs. still I get error 14009.

**Comment by amos-baron** [comment]
> > what ports do i need to open from pod segment to the VC segment
> 
> Port 443 on VC, which is used to call VC APIs from pod.

this worked
