### ISSUE TITLE
documentation is lacking in regard to vsphere integration and the plugin architecture 

### ISSUE THREAD

**Issue by amos-baron** [vmware-tanzu/velero-plugin-for-vsphere#322]
**Describe the problem/challenge you have**

[A description of the current limitation/problem/challenge that you are experiencing.]
I'm deploying the plugin on an openshift environment that with vsphere csi on a 6.7 vsphere cluster. Its been very hard to understand what are the responsibilities of each component in the plugin i.e the data-manager daemon set and the backup-driver.
in addition I cannot find what user the data-manager/backup-driver uses when authenticating with the esxi/vcenter. I need to know i order to give that user permission in the vcenter.

[A clear and concise description of what you want to happen.]
It might be a good idea to add the architecture of the plugin or at least the role of each component to make troubleshooting easier.
also, there is no documentation on how to get the plugin to work with the vcenter and just a link to the VDDK docs that apply to vcenter 7 and not 6.7

**Comment by lintongj** [comment]
@xing-yang is working on a PR that add architectural diagram at https://github.com/vmware-tanzu/velero-plugin-for-vsphere/pull/306. Please any comments are welcomed. 

```
in addition I cannot find what user the data-manager/backup-driver uses when authenticating with the esxi/vcenter. I need to know i order to give that user permission in the vcenter.
```
Currently, velero-plugin-for-vsphere shares the same credential of VCenter with vSphere CSI driver. Basically, it is whatever the VC user specified for the vSphere CSI driver is.

Also, `Prerequisites` are documented here, https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/main/docs/vanilla.md#prerequisites. Once CSI and VDDK prerequisites are satisfied, it should be good enough to use velero-plugin-for-vsphere.


FYI, there is no major change in VDDK between vSphere 7.0 and vSphere 6.7 u3 from the perspective of velero-plugin-for-vsphere. BTW, please be aware that velero-plugin-for-vsphere is supported only in vSphere 6.7 u3 and above.

**Comment by lintongj** [comment]
Close it as PR #306 is merged.
