### ISSUE TITLE
Deployment of the Velero Data Manager VM with a static IP

### ISSUE THREAD

**Issue by MarcoDima** [vmware-tanzu/velero-plugin-for-vsphere#326]
**Describe the bug**
It is currently not possible to deploy the velero DM VM with a static IP, even if the IP Allocation in the ova template points to '
Static - Manual'.

[A clear and concise description of what the bug is]
While deploying the VM within the ova template, after selecting the network in which to deploy the vm, I can see that '
IP allocation: Static - Manual' is being showed, but I cannot give an IP address from my network to be assigned the vm.

[Steps to reproduce the behavior]
In a vSphere 7 environment, just followed the installation process as stated in the docs (https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/main/docs/supervisor-datamgr.md#data-manager-virtual-machine-install) and downloaded the ova template for the velero data manager. While configuring the vm within the wizard, it is not possible to give a static ip address for the vm, and the vm gets (in my case) an ip from the dhcp of the configured network.

**Expected behavior**
I can assign a static IP in the configuration wizard and the vm gets that ip assigned.

**Comment by lintongj** [comment]
Please follow https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/turning-off-dhcp.html to turn off DHCP.

**Comment by MarcoDima** [comment]
Just turning off DHCP didn't help, so I first had to configure the static IP (https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/setting-a-static-ip-address.html) and then turn off the dhcp.

It would be nice if we could set the IP address directly within the wizard configuration.
