### ISSUE TITLE
Restore of a namespace with existing PVCs is going in infinite loop

### ISSUE THREAD

**Issue by aayush13890** [vmware-tanzu/velero-plugin-for-vsphere#340]
velero-plugin-for-vsphere version 1.1.0
Velero version 1.5.4

**Steps performed:**
1. Created a new Namespace with PVC. (Used the sample provided in Velero package - nginx with PV).
2. Performed backup of this Namespace.
3. Did not make any changes to the Namespace and triggered a restore operation using the above backup with all the resources included.
4. Restore operation gets stuck in InProgress state.

**Expected behaviour:** Restore operation should be successful.

**Few pointers which can help with the resolution of this issue:**
1. The original PVCs were not changed and they still exist with the same name on the cluster.
2. the same operation was working fine with velero-plugin-for-vsphere version 1.0.2 and Velero version 1.5.4. The restore operation completes and provides warnings for skipping resources due to conflicts.
3. Download snapshot operations seems to be failing with the below error:
    "Failed to download snapshot, ivd:0d79bc4c-2a06-4be1-83f4-49c2e087c858:4e8fbdb2-8ace-4f25-a119-57de0cbf5553, from durable object storage. Data copy failed from PE ivd:0d79bc4c-2a06-4be1-83f4-49c2e087c858, to PE ivd:0d79bc4c-2a06-4be1-83f4-49c2e087c858:4e8fbdb2-8ace-4f25-a119-57de0cbf5553: Open virtual disk file failed. The error code is 1. with error code: 1"
4. After the above failure download operation seems to be getting retried few more times. (6 times) Post this it gets marked as failed.
5. After every 20-21 minutes a new download CR is getting generated and the download operations gets triggered again with a new CR.
6. Restore operation never completes. Monitored for over 2 days. 
7. If I delete the Velero restore job and fire a new restore job (with the same backup or different), then this job gets stuck in the New phase. This may be because earlier CloneFromSnapshot is still in the pending state.

Logs files attached with debug logs enabled.
[RestoreNapespaceIssueLogs.zip](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/files/6347866/RestoreNapespaceIssueLogs.zip)

**Comment by xing-yang** [comment]
@aayush13890 As a work around, can you delete the namespace before doing the restore?  We'll fix this to skip the restore of PVCs if they already exist.

**Comment by xing-yang** [comment]
@aayush13890 You are testing on Vanilla cluster, right?  What is the Kubernetes version?

**Comment by aayush13890** [comment]
We are using VMware Tanzu v1.19.3

**Comment by aayush13890** [comment]
We have also tested against openshift version 4.5 Tanzu Kubernetes Grid Cluster and vanilla cluster.
