### ISSUE TITLE
Velero Netapp S3 Connectivity

### ISSUE THREAD

**Issue by nfeldhausen** [vmware-tanzu/velero-plugin-for-vsphere#344]
**Describe the bug**

Today we tried to deploy Velero in a vSphere 7 with Tanzu Supervisor Cluster and with Netapp Ontap 9.7P8 without Storage Grid as S3 Storage Provider. The deployment was flawless and both the backup-driver and velero pod became running.
Sadly the Backup Location stays unavailable and when creating backups the backup fails with the following error log:

`<?xml version="1.0" encoding="UTF-8"?><Error><Code>MissingSecurityHeader</Code><Message>Your request is missing a required header.</Message></Error>`

Sadly our velero pod does not provide any logs and thus the above error message is the only error message we have.

**To Reproduce**

Install Velero with Netapp as S3 Provider while using the following deployment script:

```
#!/bin/sh

NAMESPACE="velero"
BUCKET="<BUCKET>"
REGION=us-east-1
S3URL="http://<NETAPP-IP>/"
PublicURL="http://<NETAPP-IP>/"
VELERO_IMAGE=<Harbor-IP>/<Harbor-Namespace>/velero:v1.5.1
VSPHERE_PLUGIN=<Harbor-IP>/<Harbor-Namespace>/velero-plugin-for-vsphere:1.1.0
AWS_PLUGIN=<Harbor-IP>/<Harbor-Namespace>/velero-plugin-for-aws:v1.1.0

./velero-vsphere install \
    --namespace $NAMESPACE \
    --image $VELERO_IMAGE \
    --use-private-registry \
    --provider aws \
    --plugins $AWS_PLUGIN,$VSPHERE_PLUGIN \
    --bucket $BUCKET \
    --secret-file ./velero-minio-credentials \
    --snapshot-location-config region=$REGION \
    --backup-location-config region=$REGION,s3ForcePathStyle="true",s3Url=$S3URL,publicUrl=$PublicURL
```

Create a backup for a namespace

**Expected behavior**

Deploy Velero with Netapp as S3 Storage Provider.
The Backup Location should be Available.
Backups should succeed and not fail.

**Anything else you would like to add:**

Currently we are not sure if the Netapp as S3 Storage Provider is supported.
If it's not supported are there any plans to support it in the near future?

Currently used product versions:
- vCenter 7.0 U1 (Build 17491160)
- Netapp Ontap 9.7P8 without Storage Grid

**Comment by dsu-igeek** [comment]
Velero uses the AWS S3 SDK.  Have you verified that your credentials work to the NetApp S3 with the AWS command line?  The "us-east-1" region should be ignored since you've overriden the s3URL, but setting it to something like "netapp" that is not an AWS region is probably a good idea.  Can you check for activity on the S3 server to see if there are better error message there?

Complete logs from the backup and velero pods will help us to diagnose the problem.

**Comment by nfeldhausen** [comment]
We tried our Netapp S3 with the aws cli which worked fine. But while testing we saw, that with Netapp 9.7 the S3 is a product preview and might not have all functionality and is not intended to use in a production environment. So we stopped trying to deploy Velero with the Netapp S3.

Currently we aim to upgrade our Netapp to Netapp with StorageGrid which should have the necessary functionality.
As I unterstood you correct, as long as the S3 is usable with the aws cli it should work with Velero aswell. Is that correct?

In the documentation we found a list of S3 object storage providers (https://velero.io/docs/v1.6/supported-providers/#s3-compatible-object-store-providers). 
As I understand this list does not mean, that only these providers are supported. They are just verified to work with Velero by people using Velero.
Like I said before - The Storage just has to be useable with the AWS S3 CLI?

Thank you for your help :)

**Comment by lintongj** [comment]
>As I unterstood you correct, as long as the S3 is usable with the aws cli it should work with Velero aswell. Is that correct?

That is correct. Both velero and velero-plugin-for-vsphere use AWS S3 SDK. If the object store in your environment works well with AWS S3 CLI, it should work well with velero.

Please feel free to share with us your experience of using velero with Netapp S3 after the upgrade. It would be helpful to improve the list of supported object storage providers in velero documentation.

**Comment by nfeldhausen** [comment]
Today we had another try with an evaluation license of Netapp with Storage Grid.
This time the deployment went flawless. The BackupLocation shows as AVAILABLE and the backup functionality works. So everything as expected :)
As deployment script we used the same script as posted in my initial comment.

Thank you both for your help. I really appreciate it!
