### ISSUE TITLE
Plugin tries to snapshot volumes that are not VMFS and are opted into restic backups

### ISSUE THREAD

**Issue by longwa** [vmware-tanzu/velero-plugin-for-vsphere#347]
We have a mix of VMFS and NFS PVC's. When doing a backup via:

`velero backup create test-backup-4 --include-namespaces=foo`

Why does the vSphere plugin try to take a snapshot of PVC's that are not VMFS volumes? These pods are also annotated with the `backup.velero.io/backup-volumes: data` to indicate they are backed up with restic.

I can indicate `--snapshot-volumes=false` and the backup will succeed. It seems like the plugin would know not to try and backup volumes that are not CSI volume or at least could defer to restic if it sees that annotation.

Maybe there's some other configuration I'm missing between the two of them.

I'm using the plugin version v.1.1.1 (we are using Kubernetes 1.20.4 with Tanzu 1.3.0 on vSphere 6.7U3).

```
time="2021-05-01T13:24:32Z" level=info msg="1 errors encountered backup up item" backup=velero/test-foo-backup-2 logSource="pkg/backup/backup.go:427" name=foo-mysql-primary-0
time="2021-05-01T13:24:32Z" level=error msg="Error backing up item" backup=velero/test-foo-backup-2 error="pod volume backup failed: error getting snapshot id: error running command, stderr=Fatal: unable to open config file: Stat: Access Denied.\nIs there a repository at the following location?\ns3:http://172.23.60.49:9000/velero-test/restic/foo\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:179" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:431" name=foo-mysql-primary-0```

**Comment by lintongj** [comment]
Would you please follow this troubleshooting page, https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/main/docs/troubleshooting.md, to collect information and logs? Thanks.

**Comment by lintongj** [comment]
This a bug in velero-plugin-for-vsphere that need to be fixed. Working on it.
