### ISSUE TITLE
velero plugin for vsphere in air-gapped environment

### ISSUE THREAD

**Issue by aceeric** [vmware-tanzu/velero-plugin-for-vsphere#378]
I see some other references to this but none others seem to exactly match my situation.

I'm installing velero, and the velero plugin for aws, and velero plugin for vsphere in an air-gapped environment. I'm installing using the helm chart https://github.com/vmware-tanzu/helm-charts/releases/tag/velero-2.23.3

I'm specifying the following in the `initContainers` list of the `values.yaml` for the vsphere plugin:
```
- name: velero-plugin-for-vsphere
  image: my-internal-registry/velero/vsphereveleroplugin-velero-plugin-for-vsphere:v1.1.1
```
As a result, a deployment `backup-driver` is generated by the init container (I'm guessing) with image: `dpcpinternal/backup-driver:v1.1.1-rc4` which of course does not exist in our air-gapped image registry.

I need to have this image ref in the deployment patched to reference our air-gapped registry. Is there a per-design way to do this? If this is already answered elsewhere I apologize.

Thanks

**Comment by lintongj** [comment]
@aceeric Thanks for reporting this issue.

velero-plugin-for-vsphere has other two internal component, backup-driver and data-manager-for-plugin. So, you need to download the following two images and put it into your internal registry.
- vsphereveleroplugin/backup-driver:v1.1.1
- vsphereveleroplugin/data-manager-for-plugin:v1.1.1

btw, three velero-plugin-for-vsphere related images in your internal registry are required to follow the following naming convention, `<registry endpoint and path>/<repo>:<version tag>`. Currently, valid `repo`s are `velero-plugin-for-vsphere`, `backup-driver`, `data-manager-for-plugin`. So, in your case, they are something like,

- my-internal-registry/velero/vsphereveleroplugin/velero-plugin-for-vsphere:v1.1.1
- my-internal-registry/velero/vsphereveleroplugin/backup-driver:v1.1.1
- my-internal-registry/velero/vsphereveleroplugin/data-manager-for-plugin:v1.1.1

If expected backup-driver or data-manager-for-plugin image are not placed in the right place, or the expected naming convention is not followed, the fallback mechanism comes in and tries to pull image from dockerhub. That is why you observed `dpcpinternal/backup-driver:v1.1.1-rc4` is pulled.

We should have document it as a prerequisite of installing velero-plugin-for-vsphere in air-gapped environment.

**Comment by aceeric** [comment]
Ok I think I understand. Let me just confirm something. When we sync our external images into our internal registry we do some name mangling. For example: FROM docker.io/velero/velero-plugin-for-aws > TO > our-internal-registry.org/ourproject/velero-velero-plugin-for-aws. Reason is: we sync many other images from multiple registries and this helped create order from chaos. I think based on what you're saying we will have to use one of the three repos you mentioned - `velero-plugin-for-vsphere`, `backup-driver`, or `data-manager-for-plugin` or the name assignment logic will not work. If that is correct, I would suggest something: In the Helm chart, if I specify:
```
values:
  image:
    repository: our-internal-registry.org/ourproject/velero-velero
```
It would be nice if the operator would conclude from this to use the same registry and repository for all velero images. This way even though we would have to un-mangle the image name the registry and repo would be

**Comment by aceeric** [comment]
Ok - I will give this a try - I believe you're saying that image specification will "inherit" the velero operator image. So if we start the operator with the helm chart `image.repository: our-internal-registry/our-project/velero-velero:vX.Y.Z` then the operator will look for `our-internal-registry/our-project/velero-plugin-for-vsphere:v1.1.1` as long as we ensure that the repo is `velero-plugin-for-vsphere` or one of the other allowed repo values for the other images  - is that correct?

**Comment by lintongj** [comment]
That's correct. Basically, when velero deployment is created, the init containers, e.g. velero-plugin-for-vsphere, get started first, which in turn triggers the installation of velero-plugin-for-vsphere. And the installation of velero-plugin-for-vsphere will internally deploy backup-driver and data-manager-for-plugin, which will pull corresponding images from the expected internal registry if available.

**Comment by aceeric** [comment]
This worked. Thank you.
