### ISSUE TITLE
Velero backup fails with NetWorkAttachmentDefinition CR in namespace

### ISSUE THREAD

**Issue by kaimals1** [vmware-tanzu/velero-plugin-for-vsphere#389]
Environment:
k8s 1.19.2 on Ubuntu 18
VELERO_IMAGE=velero/velero:v1.6.0
VELERO_VSPHERE_PLUGIN_VERSION=v1.2.1
PPDM to perform backup
Steps:
Create a namespace
Install multus cni and create NetWorkAttachmentDefinition CR in the namespace
Backup namespace
Observation:
Backup fails with below error mesage:
time="2021-09-07T21:29:28Z" level=info msg="1 errors encountered backup up item" backup=velero-ppdm/default-2021-09-07-14-29-08-default logSource="pkg/backup/backup.go:427" name=macvlan-conf
time="2021-09-07T21:29:28Z" level=error msg="Error backing up item" backup=velero-ppdm/default-2021-09-07-14-29-08-default error="error executing custom action (groupResource=network-attachment-definitions.k8s.cni.cncf.io, namespace=default, name=macvlan-conf): rpc error: code = Unknown desc = PVC default/macvlan-conf has no volume backing this claim" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:331" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*itemBackupper).executeActions" logSource="pkg/backup/backup.go:431" name=macvlan-conf
time="2021-09-07T21:29:28Z" level=info msg="Backed up 101 items out of an estimated total of 101 (estimate will change throughout the backup)" backup=velero-ppdm/default-2021-09-07-14-29-08-default logSource="pkg/backup/backup.go:394" name=macvlan-conf namespace=default progress= resource=network-attachment-definitions.k8s.cni.cncf.io

Backup was successful once velero vsphere plugin was removed from velero deployment. 
Attached velero logs
[velerofailure.txt](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/files/7138734/velerofailure.txt)

**Comment by lintongj** [comment]
@kaimals1 would you please confirm the cluster flavor of your setup? Thanks.

We will look into the issue why the NetWorkAttachmentDefinition resource is parsed as a PVC object by plugin. 

FYI, the NetWorkAttachmentDefinition CRD is a restricted resource from [the list](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/main/docs/supervisor-notes.md#restricted-resources). When the parsing issue is fixed, the backup including the NetWorkAttachmentDefinition CR will still fail and velero backup ends up with "Partially Failed". 

The expected user behavior is to exclude the NetWorkAttachmentDefinition resource from the backup.
