### ISSUE TITLE
Update the outdated examples/demo-app.yaml

### ISSUE THREAD

**Issue by lintongj** [vmware-tanzu/velero-plugin-for-vsphere#409]
**Describe the bug**

[examples/demo-app.yaml](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/main/examples/demo-app.yaml) is pretty much outdated. We need to update it to keep aligned with most recent k8s versions

**To Reproduce**

1. Got a Vanilla k8s cluster on vSphere
2. Run the yaml to deploy a demo app.

**Expected behavior**

The demo-app YAML can deploy a demo app without any issues.

**Troubleshooting Information**

N/A

**Screenshots**

N/A

**Anything else you would like to add:**

N/A

**Comment by anooptp** [comment]
@lintongj Could you please review the PR.
