### ISSUE TITLE
Snapshot CR was not deleted after backup location deletion

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero-plugin-for-vsphere#452]
**Describe the bug**

Snapshot CR was not deleted after backup location deletion. In Velero 1.8, an [issue](https://github.com/vmware-tanzu/velero/issues/2082) was fixed, as this issue described, Snapshot CR should be deleted once the related backup storage location was deleted.

**To Reproduce**

1. Backup workload with PVs into some backup location which is named location1 in the example of  "velero --namespace velero create backup  b1 --snapshot-volumes --storage-location location1 ...... ";
2. Delete backup location  (location1);
3. Snapshot CR created during backup should be deleted, but the fact is not, Snapshot CRs still exist.

**Expected behavior**

[A clear and concise description of what you expected to happen]

**Troubleshooting Information**

[Please refer to the [Troubleshooting](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/main/docs/troubleshooting.md) page and collect the required information]

**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue]

**Comment by deepakkinni** [comment]
The Snapshot CR is uniquely a plugin concept, deleting the storage location will not delete the snapshot CRs. The Snapshot CRs are automatically deleted after 24h if the status is a success.

**Comment by danfengliu** [comment]
@deepakkinni thanks for the clarification.
