### ISSUE TITLE
Integration with Velero v1.10

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero-plugin-for-vsphere#490]
Velero v1.10 has some major refactors, some of which may impact vSphere plugin functionalities.
Some possible changes for vSphere plugin are identified in [this Velero issue](https://github.com/vmware-tanzu/velero/issues/5274) .

Please do an integration test with Velero v1.10 and address the necessary changes.

**Comment by xing-yang** [comment]
This is a dupe of https://github.com/vmware-tanzu/velero-plugin-for-vsphere/issues/485

**Comment by Lyndon-Li** [comment]
Close this one because of duplication, let's use #485 to track the entire integration of vSphere plugin with Velero 1.10.
