### ISSUE TITLE
Support for Velero 1.12.x

### ISSUE THREAD

**Issue by mymasse** [vmware-tanzu/velero-plugin-for-vsphere#550]
**Question**

Wondering if the current version of the plugin supports Velero 1.12.x or not. According to the [compatibility](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/main/docs/vanilla.md#compatibility) the current version doesn't support 1.12.

We do not want to go through a upgrades if the plugin is know to not support 1.12

**Comment by xing-yang** [comment]
It is not qualified yet.  We'll be working on it soon.

**Comment by mymasse** [comment]
Any progress on this?

**Comment by xing-yang** [comment]
https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/main/docs/vanilla.md#compatibility

**Comment by xing-yang** [comment]
It's supported now.
