### ISSUE TITLE
verero.io/vsphere image doesn't exist

### ISSUE THREAD

**Issue by ChrisJLittle** [vmware-tanzu/velero-plugin-for-vsphere#62]
I'm seeing the following when walking through the steps to get the vsphere plugin working:

`Warning  Failed     25s (x3 over 61s)  kubelet, vsan-cluster-md-0-68498d7f4f-2l9d2  Failed to pull image "velero.io/vsphere": rpc error: code = NotFound desc = failed to pull and unpack image "velero.io/vsphere:latest": failed to resolve reference "velero.io/vsphere:latest": velero.io/vsphere:latest: not found`

Has this been moved?

**Comment by lintongj** [comment]
@ChrisJLittle, velero.io/vsphere is not a name of image. It is a key to vsphere volume snapshotter plugin from velero's perspective. The released image is, vsphereveleroplugin/velero-plugin-for-vsphere:1.0.0

**Comment by ChrisJLittle** [comment]
Thanks. This was 100% user error. I though that velero.io/vsphere was a plugin and attempted to add it as such. The pod that was created and throwing the imgpullerror should  have never existed. I cleaned this up and the vsphere plugin is working as expected now.
