### ISSUE TITLE
no mention of a need for a vsphere-config-secret

### ISSUE THREAD

**Issue by ChrisJLittle** [vmware-tanzu/velero-plugin-for-vsphere#63]
In the installation instructions, there is no mention for the need to have a secret in kube-system named vsphere-config-secret. It may be assumed that this secret exists already as the vSphere CPI should be configured but it is not always named the same and may not always have the necessary paraeters in the desired format.

For example, in TKG, the secret is named csi-vsphere-config and it's contents look similar to the following:

`[Global]
insecure-flag = true
cluster-id = default/vsan-cluster

[VirtualCenter "vcsa-01a.corp.local"]
user = administrator@corp.local
password = VMware1!
datacenters = RegionA01

[Network]
public-network = DSwitch-Management`

What I found is expected with the Velero vsphere plugin is a secret in kube-system named vsphere-config-secret with contents looking similar to the following:

`[Global]
insecure-flag = true
cluster-id = default/vsan-cluster

[VirtualCenter "vcsa-01a.corp.local"]
user = administrator@corp.local
password = VMware1!
datacenters = RegionA01

[Network]
public-network = DSwitch-Management

ubuntu@cli-vm:~/velero$ cat csi-vsphere.conf
[Global]
insecure-flag = "true"
cluster-id = "default/vsan-cluster"

[VirtualCenter "vcsa-01a.corp.local"]
port = "443"
user = "administrator@corp.local"
password = "VMware1!"
datacenters = "RegionA01"

[Network]
public-network = "DSwitch-Management"`

The main things that I found were problematic were the lack of quotes and the missing port = line.

Can we get this clearly documented?

**Comment by lintongj** [comment]
@ChrisJLittle, the first released version depends on the CSI secret config in vanilla k8s setup, vsphere-config-secret, while retrieving the VC credential. However, it looks like the secret in TKG cluster differs that in vanilla k8s setup. We are going to document such known issue in the Readme.md page in a FAQ section soon.

**Comment by lintongj** [comment]
FYI, it was documented at the PR https://github.com/vmware-tanzu/velero-plugin-for-vsphere/pull/64.

**Comment by dsu-igeek** [comment]
I'm closing this, we've added this into the FAQ
