### ISSUE TITLE
unable to locate VolumeSnapshotter plugin named velero.io/vsphere

### ISSUE THREAD

**Issue by tmpkn** [vmware-tanzu/velero-plugin-for-vsphere#69]
Following the instructions to the letter. Backup attempt results in the error above.
In addition, **velero plugin get** only reports **velero.io/aws** as VolumeSnapshotter.
At the same time, repeating the plugin add command results in:
**Duplicate value: "velero-plugin-for-vsphere"**
Is it installed or not?

**Comment by lintongj** [comment]
Hi @tmpkn, would you please provide more detail about your context? such as, velero deployment and related log snippets, etc.

**Comment by dsu-igeek** [comment]
No new info, closing.  Please reopen if this continues to happen.

**Comment by MayankRathore4** [comment]
I am facing a similar issue with "replicated.com/hostpath" plugin. The error log is there while taking the backup snapshots of PVs only. Any help around this is appreciated.

**Comment by cbodonnell** [comment]
@MayankRathore4 you may need to pass the `--use-volume-snapshots=false` parameter to the `velero install` command.  The "replicated.com/hostpath" plugin is not registered as a volume snapshotter, but only as an object store.
