### ISSUE TITLE
Datamgr-for-vsphere-plugin PODS are crashing (see attached logs)

### ISSUE THREAD

**Issue by dzilbermanvmw** [vmware-tanzu/velero-plugin-for-vsphere#93]
I have installed Velero 1.4 AWS plugin 1.1.0 with 'restic' plugin and MinIO for local object store into VMware PKS (TGKI cluster).
Followed instructions in the very helpful blog: https://beyondelastic.com/2020/04/30/backup-and-migrate-tkgi-pks-to-tkg-with-velero/

I have configured vSphere snapshot plugin in the cluster that has CSI driver enabled:

**velero plugin add vsphereveleroplugin/velero-plugin-for-vsphere:1.0.0**

and ran successful backup creation using command:

**velero backup create my-ghost-backup --include-namespaces=ghost --snapshot-volumes --volume-snapshot-locations <SNAPSHOT LOCATION>**  

Backup were created successfully AFAIK:

 velero backup describe my-ghost-backup-new
Name:         my-ghost-backup-new
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.16.7+vmware.1
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=16

Phase:  Completed

Namespaces:
  Included:  ghost
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-06-15 16:47:41 +0000 UTC
Completed:  2020-06-15 16:47:57 +0000 UTC

Expiration:  2020-07-15 16:47:41 +0000 UTC

Total items to be backed up:  10
Items backed up:              10

Velero-Native Snapshots:  1 of 1 snapshots completed successfully (specify --details for more information)
--------------------------------------------------------------------------------------------------------------------------
However, deleting app names[ace and trying to restore from that backup consistently were unsuccessful. Upon examination, I have found out that 'datamgr-for-vsphere-plugin' pods are consistently crashing (see attached log files
[datamgr-for-vsphere-plugin-crashed.txt](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/files/4828080/datamgr-for-vsphere-plugin-crashed.txt)
[datamgr-for-vsphere-plugin-p9rxj-crashed.txt](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/files/4828081/datamgr-for-vsphere-plugin-p9rxj-crashed.txt)
![my-ghost_csi_backup_minIO](https://user-images.githubusercontent.com/42846514/85632596-75d60d00-b62c-11ea-872a-57e7c8337cd9.jpg)
[VELERO_INSTALL_LOCAL_MINIO.txt](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/files/4828082/VELERO_INSTALL_LOCAL_MINIO.txt)

)

**kubectl get po -n velero**
NAME                               READY   STATUS             RESTARTS   AGE
datamgr-for-vsphere-plugin-7zzfk   0/1     CrashLoopBackOff   3563       14d
datamgr-for-vsphere-plugin-kn5mw   0/1     CrashLoopBackOff   3567       14d
datamgr-for-vsphere-plugin-p9rxj   0/1     CrashLoopBackOff   3555       14d
datamgr-for-vsphere-plugin-zfp44   0/1     CrashLoopBackOff   3560       14d
minio-845c8c775b-cskd4             1/1     Running            0          16d
restic-4qsbf                       1/1     Running            0          14d
restic-8jj6g                       1/1     Running            0          16d
restic-cxplm                       1/1     Running            0          16d
restic-nqkhh                       1/1     Running            0          14d
velero-85c4f4547-msgm5             1/1     Running            0          14d

**Comment by dzilbermanvmw** [comment]
[datamgr-for-vsphere-plugin-crashed-LOG.log](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/files/4828089/datamgr-for-vsphere-plugin-crashed-LOG.log)

Pod log file attached

**Comment by swgupta-vmw** [comment]
Can you please check if the upload process had completed before the apps were deleted?
kubectl -n velero get uploads -o yaml

The upload to minio is an asynchronous process and is not currently reflected in the backup status.

**Comment by dsu-igeek** [comment]
There was an issue with PVs that are not attached to Pods hitting that nil pointer exception.  This was fixed in https://github.com/vmware-tanzu/velero-plugin-for-vsphere/pull/68 and was released as part of the 1.0.1 release.  Please try the 1.0.1 release and let us know if the issue continues.

**Comment by dzilbermanvmw** [comment]
@swgupta-vmw here is the output of 'get uploads' command:

apiVersion: v1
items:
- apiVersion: veleroplugin.io/v1
  kind: Upload
  metadata:
    creationTimestamp: "2020-06-15T16:47:57Z"
    generation: 1
    name: upload-70748cd5-aa42-486a-a31f-48f0758a6601
    namespace: velero
    resourceVersion: "3157192"
    selfLink: /apis/veleroplugin.io/v1/namespaces/velero/uploads/upload-70748cd5-aa42-486a-a31f-48f0758a6601
    uid: e915297b-0710-480b-a5f8-19a7a1968fdb
  spec:
    backupTimestamp: "2020-06-15T16:47:57Z"
    snapshotID: ivd:d2bb26ad-2f4c-47a0-a005-ec0adb593627:70748cd5-aa42-486a-a31f-48f0758a6601
  status:
    nextRetryTimestamp: "2020-06-15T16:47:57Z"
    phase: New
    progress: {}
- apiVersion: veleroplugin.io/v1
  kind: Upload
  metadata:
    creationTimestamp: "2020-06-12T04:51:25Z"
    generation: 1
    name: upload-833439b1-ff06-4c66-9dbb-d56ddb99b897
    namespace: velero
    resourceVersion: "2326964"
    selfLink: /apis/veleroplugin.io/v1/namespaces/velero/uploads/upload-833439b1-ff06-4c66-9dbb-d56ddb99b897
    uid: 75f6b754-00d4-480c-b1e1-95bd9409f5b2
  spec:
    backupTimestamp: "2020-06-12T04:51:25Z"
    snapshotID: ivd:d2bb26ad-2f4c-47a0-a005-ec0adb593627:833439b1-ff06-4c66-9dbb-d56ddb99b897
  status:
    nextRetryTimestamp: "2020-06-12T04:51:25Z"
    phase: New
    progress: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
---------------
Backups were completed and files appeared in MinIO object store browser:

 velero backup get
NAME                  STATUS                      CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
my-ghost-backup       Completed                   2020-06-12 04:51:07 +0000 UTC   17d       default            <none>
my-ghost-backup-new   Completed                   2020-06-15 16:47:41 +0000 UTC   20d       default            <none>

**Comment by dzilbermanvmw** [comment]
> There was an issue with PVs that are not attached to Pods hitting that nil pointer exception. This was fixed in #68 and was released as part of the 1.0.1 release. Please try the 1.0.1 release and let us know if the issue continues.

@dsu-igeek Thanks for commenting, unless I misread your suggestion I am running Velero 1.4 already:

ubuntu@u-cli2:~/velero$ velero version
Client:
        Version: v1.4.0
        Git commit: 5963650c9d64643daaf510ef93ac4a36b6483392
Server:
        Version: v1.4.0
------------------------------------
Or did you mean some specific "dot build" for 1.4 - could you comment pls? Thanks

**Comment by swgupta-vmw** [comment]
Thanks for the upload records.

The "phase" field is still "new". This indicates that the copy of the PV snapshot data to the remote S3 location (minio) has not yet completed, in-fact it is yet to start. We need to wait for the "phase" field to move to "Completed" before the resource being backed up can be deleted.

The backup status "Completed" indicates that the PV has been snapshotted, and NOT that the PV snapshot data has been copies from the backing volume to the durable s3 location. We need to monitor the upload CR to check if copy of the snapshot to the remote s3 bucket is complete. Note that this is required only if the resource being backed-up includes a persistent volume.

On the question about using the 1.0.1 version, this is for the velero-plugin-for-vsphere. Can you please use the newer velero-plugin-for-vsphere:1.0.1 version instead of the 1.0.0 version. You can uninstall the older version using the steps mentioned in
https://github.com/vmware-tanzu/velero-plugin-for-vsphere#uninstall-the-plugin.

**Comment by dsu-igeek** [comment]
Should be fixed with 1.0.1, please re-open if the issue continues.

**Comment by dzilbermanvmw** [comment]
Thanks for the tips @dsu-igeek - using 1.0.1 snapshot plugin:

velero plugin add vsphereveleroplugin/velero-plugin-for-vsphere:1.0.1

appears to work fine1
